# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedpost',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='approve_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.DecimalField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected')], decimal_places=0, default=0, max_digits=2),
        ),
        migrations.DeleteModel(
            name='ApprovedPost',
        ),
    ]
